"
I am DiscOrDance.
I am a tool to scrape a Discord Server and analyze its structure and content to support various development activities.
I have a domain model that extracts source code and interactions between software developers on the server.
I aim at supporting program comprehension, maintenance, and evolution by providing access to the informal documentation present on a Discord server of a community of software developers.
"
Class {
	#name : #ManifestBaselineOfDiscOrDance,
	#superclass : #PackageManifest,
	#category : #'BaselineOfDiscOrDance-Manifest'
}
